// ============================================================================
// Auth
// ============================================================================

export interface YouTubeAuthConfig {
  apiKey: string;
}

export interface YouTubeClientOptions {
  maxRetries?: number;
  timeout?: number;
}

// ============================================================================
// API Response Envelope
// ============================================================================

export interface YouTubeApiResponse<T> {
  kind: string;
  etag: string;
  items: T[];
  pageInfo: {
    totalResults: number;
    resultsPerPage: number;
  };
  nextPageToken?: string;
}

// ============================================================================
// Video
// ============================================================================

export interface VideoResource {
  id: string;
  snippet: VideoSnippet;
  contentDetails: VideoContentDetails;
  statistics: VideoStatistics;
}

export interface VideoSnippet {
  title: string;
  description: string;
  channelId: string;
  channelTitle: string;
  publishedAt: string;
  thumbnails: Record<string, Thumbnail>;
  tags?: string[];
  categoryId: string;
  defaultLanguage?: string;
  defaultAudioLanguage?: string;
}

export interface VideoContentDetails {
  duration: string;
  caption: string;
}

export interface VideoStatistics {
  viewCount: string;
  likeCount: string;
  commentCount: string;
}

export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

// ============================================================================
// Channel
// ============================================================================

export interface ChannelResource {
  id: string;
  snippet: ChannelSnippet;
  statistics: ChannelStatistics;
}

export interface ChannelSnippet {
  title: string;
  description: string;
  customUrl?: string;
  publishedAt: string;
  thumbnails: Record<string, Thumbnail>;
}

export interface ChannelStatistics {
  viewCount: string;
  subscriberCount: string;
  videoCount: string;
}

// ============================================================================
// Search
// ============================================================================

export interface SearchResult {
  id: { kind: string; videoId?: string; channelId?: string; playlistId?: string };
  snippet: {
    title: string;
    description: string;
    channelId: string;
    channelTitle: string;
    publishedAt: string;
    thumbnails: Record<string, Thumbnail>;
  };
}

export interface SearchOptions {
  maxResults?: number;
  order?: 'date' | 'rating' | 'relevance' | 'title' | 'viewCount';
  publishedAfter?: string;
  publishedBefore?: string;
  channelId?: string;
}

// ============================================================================
// Transcript
// ============================================================================

export interface TranscriptSegment {
  text: string;
  offset: number;
  duration: number;
  lang?: string;
}

export interface TranscriptResult {
  videoId: string;
  languageCode: string;
  segments: TranscriptSegment[];
  isAutoGenerated: boolean;
  fullText: string;
}

// ============================================================================
// Error Classes
// ============================================================================

export class YouTubeApiRequestError extends Error {
  constructor(
    message: string,
    public status: number,
    public code?: string,
  ) {
    super(message);
    this.name = 'YouTubeApiRequestError';
  }
}

export class YouTubeAuthenticationError extends YouTubeApiRequestError {
  constructor(message: string, status: number = 403) {
    super(message, status, 'AUTH_ERROR');
    this.name = 'YouTubeAuthenticationError';
  }
}

export class YouTubeQuotaExceededError extends YouTubeApiRequestError {
  constructor(message: string = 'YouTube Data API daily quota exceeded') {
    super(message, 403, 'QUOTA_EXCEEDED');
    this.name = 'YouTubeQuotaExceededError';
  }
}

export class YouTubeNotFoundError extends YouTubeApiRequestError {
  constructor(message: string) {
    super(message, 404, 'NOT_FOUND');
    this.name = 'YouTubeNotFoundError';
  }
}

export class YouTubeTranscriptDisabledError extends Error {
  constructor(public videoId: string) {
    super(`Transcripts are disabled for video: ${videoId}`);
    this.name = 'YouTubeTranscriptDisabledError';
  }
}

// ============================================================================
// Constants
// ============================================================================

export const DEFAULT_VIDEO_PARTS = 'snippet,contentDetails,statistics';
export const DEFAULT_CHANNEL_PARTS = 'snippet,statistics';
export const MAX_VIDEO_BATCH_SIZE = 50;
