import { YouTubeStore } from '../cache/store.js';
import { VideoResource, ChannelResource, TranscriptResult } from '../clients/types.js';

const mockVideo: VideoResource = {
  id: 'test123',
  snippet: {
    title: 'Test Video',
    description: 'A test video description',
    channelId: 'UCtest',
    channelTitle: 'Test Channel',
    publishedAt: '2026-01-01T00:00:00Z',
    thumbnails: { high: { url: 'https://img.youtube.com/vi/test123/hqdefault.jpg', width: 480, height: 360 } },
    tags: ['test', 'video'],
    categoryId: '22',
  },
  contentDetails: { duration: 'PT10M30S', caption: 'true' },
  statistics: { viewCount: '1000', likeCount: '50', commentCount: '10' },
};

const mockChannel: ChannelResource = {
  id: 'UCtest',
  snippet: {
    title: 'Test Channel',
    description: 'A test channel',
    customUrl: '@testchannel',
    publishedAt: '2020-01-01T00:00:00Z',
    thumbnails: { high: { url: 'https://img.youtube.com/channel.jpg', width: 240, height: 240 } },
  },
  statistics: { viewCount: '100000', subscriberCount: '5000', videoCount: '200' },
};

const mockTranscript: TranscriptResult = {
  videoId: 'test123',
  languageCode: 'en',
  segments: [
    { text: 'Hello world', offset: 0, duration: 2000 },
    { text: 'This is a test', offset: 2000, duration: 3000 },
  ],
  isAutoGenerated: false,
  fullText: 'Hello world This is a test',
};

describe('YouTubeStore', () => {
  let store: YouTubeStore;

  beforeEach(() => {
    // In-memory SQLite for testing
    store = new YouTubeStore(':memory:');
  });

  afterEach(() => {
    store.close();
  });

  describe('videos', () => {
    it('upserts and retrieves a video', () => {
      store.upsertVideo(mockVideo);
      const result = store.getVideo('test123');
      expect(result).toBeDefined();
      expect(result!.id).toBe('test123');
      expect(result!.snippet.title).toBe('Test Video');
      expect(result!.statistics.viewCount).toBe('1000');
    });

    it('returns undefined for missing video', () => {
      expect(store.getVideo('nonexistent')).toBeUndefined();
    });

    it('updates on re-upsert', () => {
      store.upsertVideo(mockVideo);
      const updated = { ...mockVideo, statistics: { ...mockVideo.statistics, viewCount: '2000' } };
      store.upsertVideo(updated);
      const result = store.getVideo('test123');
      expect(result!.statistics.viewCount).toBe('2000');
    });
  });

  describe('channels', () => {
    it('upserts and retrieves a channel', () => {
      store.upsertChannel(mockChannel);
      const result = store.getChannel('UCtest');
      expect(result).toBeDefined();
      expect(result!.snippet.title).toBe('Test Channel');
      expect(result!.statistics.subscriberCount).toBe('5000');
    });

    it('returns undefined for missing channel', () => {
      expect(store.getChannel('nonexistent')).toBeUndefined();
    });
  });

  describe('transcripts', () => {
    it('upserts and retrieves a transcript', () => {
      store.upsertVideo(mockVideo); // FK requires video to exist
      store.upsertTranscript('test123', mockTranscript);
      const result = store.getTranscript('test123', 'en');
      expect(result).toBeDefined();
      expect(result!.fullText).toBe('Hello world This is a test');
      expect(result!.segments).toHaveLength(2);
    });

    it('returns undefined for missing transcript', () => {
      expect(store.getTranscript('nonexistent')).toBeUndefined();
    });
  });

  describe('stats', () => {
    it('returns correct counts', () => {
      store.upsertVideo(mockVideo);
      store.upsertChannel(mockChannel);
      store.upsertTranscript('test123', mockTranscript);

      const stats = store.getStats();
      expect(stats.videos).toBe(1);
      expect(stats.channels).toBe(1);
      expect(stats.transcripts).toBe(1);
      expect(stats.lastSync).toBeDefined();
    });

    it('returns zeros for empty store', () => {
      const stats = store.getStats();
      expect(stats.videos).toBe(0);
      expect(stats.channels).toBe(0);
      expect(stats.transcripts).toBe(0);
      expect(stats.lastSync).toBeNull();
    });
  });
});
