import { TranscriptSkill } from '../skills/transcript/index.js';
import { YouTubeClient } from '../clients/youtube-client.js';
import { YouTubeStore } from '../cache/store.js';
import { VideoResource, TranscriptResult } from '../clients/types.js';

const mockVideo: VideoResource = {
  id: 'dQw4w9WgXcQ',
  snippet: {
    title: 'Test Video',
    description: 'Description',
    channelId: 'UCtest',
    channelTitle: 'Test Channel',
    publishedAt: '2026-01-01T00:00:00Z',
    thumbnails: {},
    categoryId: '22',
  },
  contentDetails: { duration: 'PT5M', caption: 'true' },
  statistics: { viewCount: '100', likeCount: '10', commentCount: '5' },
};

const mockTranscript: TranscriptResult = {
  videoId: 'dQw4w9WgXcQ',
  languageCode: 'en',
  segments: [
    { text: 'Hello', offset: 0, duration: 1000 },
    { text: 'World', offset: 1000, duration: 1000 },
  ],
  isAutoGenerated: false,
  fullText: 'Hello World',
};

describe('TranscriptSkill', () => {
  let skill: TranscriptSkill;
  let mockClient: jest.Mocked<YouTubeClient>;
  let store: YouTubeStore;

  beforeEach(() => {
    store = new YouTubeStore(':memory:');
    mockClient = {
      getVideo: jest.fn().mockResolvedValue(mockVideo),
      getVideos: jest.fn().mockResolvedValue([mockVideo]),
      getChannel: jest.fn(),
      searchVideos: jest.fn(),
      getTranscript: jest.fn().mockResolvedValue(mockTranscript),
    } as unknown as jest.Mocked<YouTubeClient>;

    skill = new TranscriptSkill(mockClient, store);
  });

  afterEach(() => {
    store.close();
  });

  describe('fetchTranscript', () => {
    it('fetches and caches transcript on first call', async () => {
      const result = await skill.fetchTranscript('dQw4w9WgXcQ');
      expect(result.video.id).toBe('dQw4w9WgXcQ');
      expect(result.transcript.fullText).toBe('Hello World');
      expect(result.fromCache).toBe(false);
      expect(mockClient.getVideo).toHaveBeenCalledWith('dQw4w9WgXcQ');
      expect(mockClient.getTranscript).toHaveBeenCalledWith('dQw4w9WgXcQ', 'en');
    });

    it('returns from cache on second call', async () => {
      await skill.fetchTranscript('dQw4w9WgXcQ');
      const result = await skill.fetchTranscript('dQw4w9WgXcQ');
      expect(result.fromCache).toBe(true);
      // Client should only be called once (first fetch)
      expect(mockClient.getVideo).toHaveBeenCalledTimes(1);
    });

    it('force re-fetches with refresh option', async () => {
      await skill.fetchTranscript('dQw4w9WgXcQ');
      await skill.fetchTranscript('dQw4w9WgXcQ', { refresh: true });
      expect(mockClient.getVideo).toHaveBeenCalledTimes(2);
    });

    it('extracts video ID from URL', async () => {
      await skill.fetchTranscript('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
      expect(mockClient.getVideo).toHaveBeenCalledWith('dQw4w9WgXcQ');
    });

    it('formats with timestamps when requested', async () => {
      const result = await skill.fetchTranscript('dQw4w9WgXcQ', { includeTimestamps: true });
      expect(result.formatted).toContain('[00:00]');
      expect(result.formatted).toContain('[00:01]');
    });
  });

  describe('fetchVideoMetadata', () => {
    it('fetches and caches video metadata', async () => {
      const result = await skill.fetchVideoMetadata('dQw4w9WgXcQ');
      expect(result.video.snippet.title).toBe('Test Video');
      expect(result.fromCache).toBe(false);
    });

    it('returns from cache on second call', async () => {
      await skill.fetchVideoMetadata('dQw4w9WgXcQ');
      const result = await skill.fetchVideoMetadata('dQw4w9WgXcQ');
      expect(result.fromCache).toBe(true);
    });
  });

  describe('stats', () => {
    it('reports cache stats', async () => {
      await skill.fetchTranscript('dQw4w9WgXcQ');
      const stats = skill.stats();
      expect(stats.videos).toBe(1);
      expect(stats.transcripts).toBe(1);
    });
  });
});
